name: iris-app
options:
  bundleIdPrefix: com.dylan
  deploymentTarget:
    iOS: "17.0"

targets:
  iris-app:
    type: application
    platform: iOS
    sources:
      - iris-app
    settings:
      base:
        INFOPLIST_FILE: iris-app/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.dylan.iris.iphone
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
