name: iris-app
options:
  bundleIdPrefix: com.iris
  deploymentTarget:
    iOS: "17.0"

targets:
  iris-app:
    type: application
    platform: iOS
    configFiles:
      Debug: iris-app/Configs/App.xcconfig
      Release: iris-app/Configs/App.xcconfig
    sources:
      - iris-app
    settings:
      base:
        INFOPLIST_FILE: iris-app/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(IRIS_BUNDLE_ID)
        'PRODUCT_BUNDLE_IDENTIFIER[sdk=iphoneos*]': $(IRIS_BUNDLE_ID_DEVICE)
        DEVELOPMENT_TEAM: $(IRIS_DEVELOPMENT_TEAM)
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
